# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Mohammed Shifreen, Full Stack Web Developer
email: mshifreen@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mshifreen.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title
logo: /assets/img/me.jpg

# Webmaster tools verifications
webmaster_verifications:
  google: IEZmD4FTSIHT4pRgJo17oebGPG57rdV0_Cem7B2ONWs

# Social media details
github_username:  Shifrin
linkedin_username:  mshifreen
stackoveflow_userid:  1933627
stackoveflow_username:  shifrin
freecodecamp_username: shifrin

# Build settings
markdown: kramdown

# Paginate settings
paginate: 10
paginate_path: "/blog/page/:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
